// Auto-generated by scripts/capture-website.mjs — do not edit by hand.
export const CONCEPT2_PAGE_WIDTH = 1920;
export const CONCEPT2_PAGE_HEIGHT = 7890;

export type Concept2Section = {
  id: string;
  label: string;
  top: number;
  height: number;
};

export const CONCEPT2_SECTIONS: Concept2Section[] = [
  { id: "home", label: "Dance Create Perform", top: 0, height: 1185 },
  { id: "space", label: "More Than A Class", top: 1185, height: 1185 },
  { id: "classes", label: "Dance Classes", top: 2370, height: 1178 },
  { id: "coaches", label: "Meet The Team", top: 3548, height: 1071 },
  { id: "schedule", label: "Class Schedule", top: 4620, height: 837 },
  { id: "reviews", label: "What They Say", top: 5457, height: 587 },
  { id: "contact", label: "Start Your Journey", top: 6044, height: 874 }
];
