import puppeteer from "puppeteer";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, resolve } from "node:path";
import { writeFileSync, mkdirSync } from "node:fs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const repoRoot = resolve(projectRoot, "..");

const htmlPath = resolve(repoRoot, "dance-studio-website-concept-2.html");
const outDir = resolve(projectRoot, "public");
const outImage = resolve(outDir, "concept2-fullpage.png");
const outMeta = resolve(projectRoot, "src", "concept2-meta.ts");

mkdirSync(outDir, { recursive: true });

const VIEWPORT_WIDTH = 1920;

console.log("Launching browser…");
const browser = await puppeteer.launch({
  headless: true,
  defaultViewport: { width: VIEWPORT_WIDTH, height: 1080, deviceScaleFactor: 1 },
});

const page = await browser.newPage();

console.log("Loading page:", htmlPath);
const url = pathToFileURL(htmlPath).href;
await page.goto(url, { waitUntil: "networkidle0", timeout: 90000 });

// Wait extra for fonts and any lazy images
await page.evaluate(() => document.fonts.ready);
await new Promise((r) => setTimeout(r, 1500));

// Measure full page height after layout
const pageHeight = await page.evaluate(() => {
  return Math.max(
    document.documentElement.scrollHeight,
    document.body.scrollHeight,
  );
});
console.log(`Page height: ${pageHeight}px`);

// Trigger any scroll-based animations by scrolling through and back
await page.evaluate(async (h) => {
  await new Promise((res) => {
    let y = 0;
    const step = () => {
      window.scrollTo(0, y);
      y += 400;
      if (y < h) {
        setTimeout(step, 30);
      } else {
        window.scrollTo(0, 0);
        setTimeout(res, 400);
      }
    };
    step();
  });
}, pageHeight);

// Extract section positions from the page (by id + selector)
// IMPORTANT: measure BEFORE any viewport resize so min-height: 100vh stays at 1080px
const sectionTargets = [
  { id: "home", label: "Dance Create Perform" },
  { id: "space", label: "More Than A Class" },
  { id: "classes", label: "Dance Classes" },
  { id: "coaches", label: "Meet The Team" },
  { id: "schedule", label: "Class Schedule" },
  { id: "reviews", label: "What They Say" },
  { id: "contact", label: "Start Your Journey" },
];

const sectionRects = await page.evaluate((targets) => {
  return targets
    .map((t) => {
      const el = document.getElementById(t.id);
      if (!el) return null;
      const r = el.getBoundingClientRect();
      const top = r.top + window.scrollY;
      return {
        id: t.id,
        label: t.label,
        top: Math.round(top),
        height: Math.round(r.height),
      };
    })
    .filter(Boolean);
}, sectionTargets);

console.log("Capturing screenshot…");
await page.screenshot({
  path: outImage,
  fullPage: true,
  type: "png",
});

await browser.close();

const sectionsLiteral = sectionRects
  .map(
    (s) =>
      `  { id: "${s.id}", label: "${s.label.replace(/"/g, '\\"')}", top: ${s.top}, height: ${s.height} }`,
  )
  .join(",\n");

writeFileSync(
  outMeta,
  `// Auto-generated by scripts/capture-website.mjs — do not edit by hand.\n` +
    `export const CONCEPT2_PAGE_WIDTH = ${VIEWPORT_WIDTH};\n` +
    `export const CONCEPT2_PAGE_HEIGHT = ${pageHeight};\n\n` +
    `export type Concept2Section = {\n` +
    `  id: string;\n` +
    `  label: string;\n` +
    `  top: number;\n` +
    `  height: number;\n` +
    `};\n\n` +
    `export const CONCEPT2_SECTIONS: Concept2Section[] = [\n${sectionsLiteral}\n];\n`,
  "utf8",
);

console.log("Saved:", outImage);
console.log("Saved:", outMeta);
console.log("Done.");
